spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 100604



mybatis:
    mapper-locations: classpath:mapper/*.xml
    #config-location: classpath:mybatis-config.xml
    #type-aliases-package: com.example.demo.object